version: '3.8'

services:
  api:
    build: .
    container_name: ex08-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    configs:
      - source: api-config
        target: /etc/app/config.yml
        mode: "0440"
    environment:
      - NODE_ENV=development
    networks:
      - secure-network

configs:
  api-config:
    file: ./config.yml

networks:
  secure-network:
    driver: bridge
